better_exposed_filters.filter.bef_select:
  label: 'BEF Select'
  type: better_exposed_filters_filter_widget
  mapping:
    query_tags:
      type: string
      label: 'Options query tags'
    max_results:
      type: integer
      label: 'Maximum number of select options'
    order_by:
      type: string
      label: 'How the options will be sorted'